id: demo2
namespace: testes
description: Hello World

inputs:
  - id: user
    type: STRING
    defaults: Batfause

tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: Aliviados

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'

  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      a BatCaverna está segura, {{ inputs.user }}! 
      estamos {{ outputs.first_task.value}} de ter vc aqui

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: 0 9 * * *
