name: Kestra CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Kestra Validate
    steps:
      - name: Checkout content
        uses: actions/checkout@v4
        
      - name: Validate flows
        uses: kestra-io/validate-action@master       
        with:
          directory: ./kestra/flows
          resource: flow
          server: https://0b73-45-230-85-67.ngrok-free.app

          
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
