name: Kestra CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Kestra Validate
    steps:
      - name: Checkout content
        uses: actions/checkout@v4
        
      - name: Validate flows
        uses: kestra-io/validate-action@master       
        with:
          directory: ./kestra/flows
          resource: flow
          server: https://10e0-45-184-68-200.ngrok-free.app

  deploy:
    runs-on: ubuntu-latest
    name: Kestra deploy
    steps:
      - name: Checkout content
        uses: actions/checkout@v4
          
      - name: Deploy flows
        uses: kestra-io/validate-action@master       
        with:
          namespace: company.team
          directory: ./kestra/flows
          resource: flow
          server: https://10e0-45-184-68-200.ngrok-free.app

        

