name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Rodar testes
      #  run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy para produção
        run: |
          echo "Rodando deploy em produção..."
          # Aqui pode entrar um script de deploy via SSH ou Docker
