name: Trigger Kestra Workflow via ngrok

on:
  push:
    branches:
      - main  

jobs:
  trigger_kestra:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar o workflow do Kestra via ngrok
        run: |
          curl -X POST " https://ecb4-45-230-85-179.ngrok-free.app/api/v1/executions/trigger/default/hello-devops" -F "param=value"\

