name: Trigger Kestra Workflow via ngrok

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que deseja monitorar

jobs:
  trigger_kestra:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar o workflow do Kestra via ngrok
        run: |
          curl -X POST "https://7d6c-45-230-85-179.ngrok-free.app/api/v1/executions/trigger/default/hello-devops" \
               -H "Content-Type: application/json" \
               -d '{"param": "value"}'
