name: Trigger Kestra Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-kestra:
    runs-on: ubuntu-latest
    services:
      kestra:
        image: kestra/kestra:latest
        ports:
          - 8080:8080
    steps:
      - name: Wait for Kestra to start
        run: sleep 20  # Aguarde alguns segundos para o serviço subir

      - name: Send request to Kestra API
        run: |
          curl -X POST "http://localhost:8080/api/v1/executions/trigger/default/hello-devops" -F "param=value"
