name: Trigger Kestra Workflow

on:
  push:
    branches:
      - main  # Ou qualquer branch que deseja monitorar

jobs:
  trigger_kestra:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar o workflow do Kestra
        run: |
          curl -X POST "http://localhost:8080/api/v1/executions/trigger/default/hello-devops" \
               -H "Content-Type: application/json" \
               -d '{"param": "value"}'
